name: Backend CI (FastAPI)

on:
  push:
    branches:
      - '**'

jobs:
  run-test:
    name: Test Backend
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Backend Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run tests
        env:
          DATABASE_URL: sqlite+aiosqlite:///Chinook_Sqlite.sqlite
          SECRET_KEY: '091283nbjsadabsjhd81o23nasdkjnasdasdbv'
        run: |
          pytest
